apiVersion: v1
kind: Service
metadata:
  name: flask-hello-app-service
spec:
  selector:
    app: flask-hello-app
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 30036
  type: LoadBalancer